### ISSUE TITLE
Does not work with python 3.4 and Django >= 1.8

### ISSUE THREAD

**Issue by LennyLip** [jmcclell/django-bootstrap-pagination#33]
```
bootstrap_pagination\templatetags\bootstrap_pagination.py", line 151, in render
    page_count = page.paginator.num_pages
AttributeError: 'str' object has no attribute 'paginator'
```

in debugger
page=''

**Comment by LennyLip** [comment]
My mistake.
But need more docs!
I think, that page_obj its query for pagination (and it will be cool).

For other user - page_obj it result of 
page_obj = paginator.page() in a view

**Comment by LennyLip** [comment]
http://stackoverflow.com/a/31849909/1271271
maybe my answert will help someone
